#!/bin/bash

if [[ ! -f $OVPN_DATA/etc/openvpn ]]; then
  docker run -v $OVPN_DATA:/etc/openvpn \
    --rm kylemanna/openvpn ovpn_genconfig \
    -u udp://$(curl https://whatsmyip.co | xargs)

  METADATA="http://169.254.169.254/latest/meta-data"
  MAC_ADDR=$(curl -s $METADATA/network/interfaces/macs/ | head -n1 | tr -d '/')
  CIDR_BLOCK=$(curl -s $METADATA/network/interfaces/macs/$MAC_ADDR/vpc-ipv4-cidr-block/)

  sudo chown -R $OVPN_DATA

  echo "push \"dhcp-option DNS $(bash ./cidr-to-ip.sh $CIDR_BLOCK | sed -n 3p)\"" \
    >> $OVPN_DATA/openvpn.conf
  echo "duplicate-cn" >> $OVPN_DATA/openvpn.conf
  echo "max-clients 30" >> $OVPN_DATA/openvpn.conf

fi

if [[ ! -d $OVPN_DATA/pki ]]; then
  docker run -v $OVPN_DATA:/etc/openvpn \
    --rm -it kylemanna/openvpn ovpn_initpki nopass
fi


docker run -v $OVPN_DATA:/etc/openvpn -d \
  -p 1194:1194/udp \
  --log-driver json-file \
  --log-opt max-size=10m \
  --log-opt max-file=100 \
  --cap-add=NET_ADMIN kylemanna/openvpn
